# Config file for automatic testing at travis-ci.org

language: python

python:
    - "2.7"

sudo: false



# Run Python tests (core and addon) and JS tests
script:
    - echo "test"

notifications: 
    slack: h-itg-dev:4z5R67svHYtxSBd3o6dsZHrT 
    webhooks: 
      urls: 
        - http://52.68.213.92:8888/webhook 
      on_failure: never # default: always 

